export const scenes = [
  {
    id: "origin",
    label: "Origin",
    kicker: "Coffee village in Monteverde",
    title: "It begins in two hands.",
    body: "A family story carried by coffee, work and a living landscape.",
    tags: ["San Luis", "Monteverde"],
    still: "/assets/montanoa-coffee-hands-start-16x9.webp",
    focal: "68% 46%",
    accent: "var(--gold)",
    clip: "/assets/video/montanoa-into-farm-scrub-web.mp4",
    clipMobile: "/assets/video/montanoa-into-farm-scrub-mobile-web.mp4",
  },
  {
    id: "craft",
    label: "From cherry to cup",
    kicker: "Grown, harvested, shared",
    title: "Every step leaves a flavor.",
    body: "Walk the real process—from shade-grown cherries and manual harvest to drying, tasting and the knowledge shared at Montanoa Academy.",
    tags: ["Grow", "Harvest", "Learn"],
    still: "/assets/original/academy-0706.jpeg",
    poster: "/assets/video/montanoa-farm-to-craft-poster.webp",
    focal: "58% 50%",
    accent: "var(--harvest)",
    clip: "/assets/video/montanoa-farm-to-craft-scrub-web.mp4",
    clipMobile: "/assets/video/montanoa-farm-to-craft-scrub-mobile-web.mp4",
  },
  {
    id: "stay",
    label: "Stay where it begins",
    kicker: "A nature retreat",
    title: "Wake up inside the story.",
    body: "Stay on the hillside among tropical birds, cloud-forest mountains and the distant light of the Gulf of Nicoya.",
    tags: ["Guest house", "San Luis"],
    still: "/assets/original/stay-0001.jpeg",
    poster: "/assets/video/montanoa-craft-to-stay-poster.webp",
    focal: "48% 52%",
    accent: "var(--sun)",
    clip: "/assets/video/montanoa-craft-to-stay-scrub-web.mp4",
    clipMobile: "/assets/video/montanoa-craft-to-stay-scrub-mobile-web.mp4",
  },
];
